In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
data=pd.read_csv('/content/drive/MyDrive/ANN dataset/Churn_Modelling.csv')

In [4]:
data.head()


RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [5]:
X = data.iloc[:, 3:13].values
y = data.iloc[:, 13].values

In [6]:
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
labelencoder=LabelEncoder()
data['Gender'] = labelencoder.fit_transform(data['Gender'])
data.head()


RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary  Exited
0          1    15634602  Hargrave  ...               1       101348.88       1
1          2    15647311      Hill  ...               1       112542.58       0
2          3    15619304      Onio  ...               0       113931.57       1
3          4    15701354      Boni  ...               0        93826.63       0
4          5    15737888  Mitchell  ...               1        79084.10       0

[5 rows x 14 columns]

In [9]:

'''from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
Geography = asarray([['France'], ['Spain'], ["Germany"]])
print(Geography)

encoder = OneHotEncoder(sparse=False)

onehot = encoder.fit_transform(Geography)
print(onehot)'''

'from numpy import asarray\nfrom sklearn.preprocessing import OneHotEncoder\nGeography = asarray([[\'France\'], [\'Spain\'], ["Germany"]])\nprint(Geography)\n\nencoder = OneHotEncoder(sparse=False)\n\nonehot = encoder.fit_transform(Geography)\nprint(onehot)'

In [10]:
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
labelencoder=LabelEncoder()
data['Geography'] = labelencoder.fit_transform(data['Geography'])
data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember  EstimatedSalary  Exited
0          1    15634602  Hargrave  ...               1        101348.88       1
1          2    15647311      Hill  ...               1        112542.58       0
2          3    15619304      Onio  ...               0        113931.57       1
3          4    15701354      Boni  ...               0         93826.63       0
4          5    15737888  Mitchell  ...               1         79084.10       0

[5 rows x 14 columns]

In [11]:
X = data.iloc[:, 3:13].values
y = data.iloc[:, 13].values

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [14]:
ann = tf.keras.models.Sequential()

#add input and hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#Adding the 2nd hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [15]:
ann.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [16]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
219/219 [==============================] - 1s 2ms/step - loss: 0.8129 - accuracy: 0.4186
Epoch 2/100
219/219 [==============================] - 0s 2ms/step - loss: 0.5785 - accuracy: 0.7837
Epoch 3/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4910 - accuracy: 0.7991
Epoch 4/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4563 - accuracy: 0.8041
Epoch 5/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4397 - accuracy: 0.8130
Epoch 6/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4287 - accuracy: 0.8214
Epoch 7/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4203 - accuracy: 0.8276
Epoch 8/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4131 - accuracy: 0.8313
Epoch 9/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4067 - accuracy: 0.8373
Epoch 10/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4003 - accura

In [17]:
y_pred=ann.predict(X_test)
y_pred

array([[0.08488411],
       [0.12605062],
       [0.05937359],
       ...,
       [0.08882037],
       [0.17748916],
       [0.05726415]], dtype=float32)

In [18]:
# Customer with GEOGRAPHY : FRANCE,  CREDIT SCORE= 600", GENDER: MALE,  AGE =40YEARS , TENURE: 3YEARS , BALANCE 60000, NO OF PRODUCTS : 2, CREDIT CARD : YES,  ACTIVE MEMBER: YES , ESTIMATED SALARY : 50000
ann.predict(sc.transform([[600,0, 1, 40, 3,60000, 2,1, 1, 50000]])> 0.5)


array([[0.02528965]], dtype=float32)

In [19]:
y_pred= ann.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred


array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [22]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm


array([[2291,   82],
       [ 347,  280]])

In [23]:
acc=accuracy_score(y_test,y_pred)
acc

0.857