In [ ]:
A = [[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]


In [ ]:
print("A =", A)

A = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]


In [ ]:
print("A[1] =", A[1])

A[1] = [-5, 8, 9, 0]


In [ ]:
print("A[1][2] =", A[1][2])

A[1][2] = 9


In [ ]:
print("A[0][-1] =", A[0][-1])

A[0][-1] = 12


In [ ]:
column = [];        # empty list
for row in A:
  column.append(row[2])   


In [ ]:
print("3rd column =", column)

3rd column = [5, 9, 11]


In [ ]:
import numpy as np

zeors_array = np.zeros( (2, 3) )
print(zeors_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np

A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)

A = np.array([[1.1, 2, 3], [3, 4, 5]]) # Array of floats
print(A)

A = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # Array of complex numbers
print(A)

[[1 2 3]
 [3 4 5]]
[[1.1 2.  3. ]
 [3.  4.  5. ]]
[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]


In [ ]:
import numpy as np

zeors_array = np.zeros( (2, 3) )
print(zeors_array)


ones_array = np.ones( (1, 5), dtype=np.int32 ) 

print(ones_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1 1 1]]


In [ ]:
import numpy as np

A = np.arange(4)
print('A =', A)

B = np.arange(12).reshape(2, 6)
print('B =', B)

A = [0 1 2 3]
B = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
import numpy as np

A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
C = A + B      # element wise addition
print(C)

[[11  1]
 [ 8  0]]


In [ ]:
import numpy as np

A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = A.dot(B)
print(C)


[[ 36 -12]
 [ -1   2]]


In [ ]:
import numpy as np

A = np.array([[1, 1], [2, 1], [3, -3]])
print(A.transpose())


[[ 1  2  3]
 [ 1  1 -3]]


In [ ]:
import numpy as np
A = np.array([2, 4, 6, 8, 10])

print("A[0] =", A[0])     # First element     
print("A[2] =", A[2])     # Third element 
print("A[-1] =", A[-1])   # Last element     

A[0] = 2
A[2] = 6
A[-1] = 10


In [ ]:
import numpy as np

A = np.array([[1, 4, 5, 12],
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

#  First element of first row
print("A[0][0] =", A[0][0])  

# Third element of second row
print("A[1][2] =", A[1][2])

# Last element of last row
print("A[-1][-1] =", A[-1][-1])

A[0][0] = 1
A[1][2] = 9
A[-1][-1] = 19


In [ ]:
import numpy as np

A = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

print("A[0] =", A[0]) # First Row
print("A[2] =", A[2]) # Third Row
print("A[-1] =", A[-1]) # Last Row (3rd row in this case)

A[0] = [ 1  4  5 12]
A[2] = [-6  7 11 19]
A[-1] = [-6  7 11 19]


In [ ]:
import numpy as np
letters = np.array([1, 3, 5, 7, 9, 7, 5])

# 3rd to 5th elements
print(letters[2:5])        # Output: [5, 7, 9]

# 1st to 4th elements
print(letters[:-5])        # Output: [1, 3]   

# 6th to last elements
print(letters[5:])         # Output:[7, 5]

# 1st to last elements
print(letters[:])          # Output:[1, 3, 5, 7, 9, 7, 5]

# reversing a list
print(letters[::-1])          # Output:[5, 7, 9, 7, 5, 3, 1]


[5 7 9]
[1 3]
[7 5]
[1 3 5 7 9 7 5]
[5 7 9 7 5 3 1]


In [ ]:
import numpy as np

A = np.array([[1, 4, 5, 12, 14], 
    [-5, 8, 9, 0, 17],
    [-6, 7, 11, 19, 21]])

print(A[:2, :4])
print(A[:1,])

[[ 1  4  5 12]
 [-5  8  9  0]]
[[ 1  4  5 12 14]]


In [ ]:

from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)
B = array([[1, 2, 3], [4, 5, 6]])
print(B)
C = A + B
print(C)


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
import numpy as np
	
x = np.matrix([[1, 2], [4, 3]])
y = np.matrix([[3, 4], [3, 10]])
	

print(x.shape)
	# (2, 2)
print(y.shape)
	# (2, 2)
	

m_sum = np.add(x, y)
print(m_sum)
print(m_sum.shape)


(2, 2)
(2, 2)
[[ 4  6]
 [ 7 13]]
(2, 2)


In [ ]:
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)
B = array([[1, 2, 3], [4, 5, 6]])
print(B)
C = A / B
print(C)


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)
B = array([[1, 2, 3], [4, 5, 6]])
print(B)
C = A * B
print(C)


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


In [ ]:
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)
B = array([[0.5, 0.5, 0.5], [0.5, 0.5, 0.5]])
print(B)
C = A - B
print(C)

[[1 2 3]
 [4 5 6]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
[[0.5 1.5 2.5]
 [3.5 4.5 5.5]]


In [ ]:
import numpy as np
	

x = np.matrix([[1, 2], [4, 3]])
s_sum = x + 1
print(s_sum) 
#1 will act as [1,1],[1,1]


[[2 3]
 [5 4]]


In [ ]:
import numpy as np


x = np.matrix([[1, 2], [4, 3]])
s_mul = x * 3
print(s_mul)


[[ 3  6]
 [12  9]]


In [5]:
import numpy as np
	

a =np.arange()
b = np.array([1, 2])
c=np.matmul(a, b)
'''print(c)
complex_mul = np.matmul([2j, 3j], [2j, 3j])
print(complex_mul)'''


TypeError: ignored

In [ ]:
import numpy as np


a = np.array([[1, 2], [3, 4]])
print(a)
a=a.transpose()
print(a)


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [ ]:
# Python program to inverse
# a matrix using numpy

# Import required package
import numpy as np

# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
			[4, -2, 5],
			[2, 8, 7]])

# Calculating the inverse of the matrix
print(np.linalg.inv(A))


[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
